services:
    backend:
        image: backend
        container_name: backend
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        privileged: true
        volumes:
            # Settings File and Placeholder Photo
            - ./.env:/app/.env
            - ./staticfiles:/tmp/app/staticfiles
            - ./mediafiles:/app/mediafiles
        environment:
            - TZ=Europe/Sofia
        ports:
            - 8000:8000
    nginx:
        container_name: core_web
        restart: on-failure
        image: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./staticfiles:/app/staticfiles
            - ./mediafiles:/app/mediafiles
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/logs:/var/log/nginx
        depends_on:
            - backend
