# Generated by Django 5.1.3 on 2024-12-02 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shop_images/')),
                ('image_name', models.CharField(blank=True, max_length=255)),
                ('shop_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.shopitem')),
            ],
        ),
    ]
